app: diffusion_decoder
nodes: 16
tasks_per_node: 8

data:
  dataset_type: VideoDataset
  datasets:
    - data/CLIP4MC_Dataset/train.csv
  decode_one_clip: true #not using
  batch_size: 4
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 224
  patch_size: 16
  pin_mem: true
  num_workers: 4
  filter_short_videos: false
  clip_duration: null

data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0

logging:
  folder: logs/train/diffusion_decoder_vitl16
  write_tag: diffusion_decoder

meta:
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  use_sdpa: true
  dtype: bfloat16
  pre_train_model: weights/vitl16.pth.tar
  gradient_checkpointing: true
  save_every_freq: 50

model:
  model_name: vit_large
  uniform_power: true

diffusion:
  in_channels: 4
  out_channels: 4
  sample_size: 32
  layers_per_block: 4
  attention_head_dim: 64
  dropout: 0.1
  block_out_channels:
    - 128
    - 256
    - 512
    - 512
  down_block_types:
    - "CrossAttnDownBlock2D"
    - "CrossAttnDownBlock2D"
    - "CrossAttnDownBlock2D"
    - "CrossAttnDownBlock2D"
  up_block_types:
    - "CrossAttnUpBlock2D"
    - "CrossAttnUpBlock2D"
    - "CrossAttnUpBlock2D"
    - "CrossAttnUpBlock2D"
  scheduler_prediction_type: "v_prediction"
  do_latent_diffusion: true
  do_edm_style_training: true
  vae_model_id: stabilityai/stable-diffusion-xl-base-1.0
  cross_attn_cond: true
  in_concat_cond: false


optimization:
  ipe: null
  lr_scheduler_type: constant
  lr: 2.0e-5
  clip_grad: 1.0
  epochs: 150
  warmup: 10
  betas:
    - 0.9
    - 0.999
  weight_decay: 1.0e-2
  eps: 1.0e-8